<a href="https://colab.research.google.com/github/kwjdals/2020-2-AI/blob/master/code/02_tf_interm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import tensorflow as tf
tf.__version__

'2.3.0'

In [13]:
tf.executing_eagerly()

True

In [14]:
m = tf.constant([[1,2],[3,4]])
print(m)
print(m.numpy())

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
[[1 2]
 [3 4]]


In [15]:
x =[[2.]]
m = tf.matmul(x,x)
print(m)
print(m.numpy())

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)
[[4.]]


In [16]:
x=[2.]
m = tf.matmul(x,x)

InvalidArgumentError: ignored

In [17]:
matrix1 = tf.constant([[1.,2.],[3. ,4.]])
matrix2 = tf.constant([[2.,0.],[1. ,2.]])

gop = tf.matmul(matrix1, matrix2)
print(gop.numpy())

[[ 4.  4.]
 [10.  8.]]


In [18]:
gop = tf.matmul(matrix2, matrix1)
print(gop.numpy())

[[ 2.  4.]
 [ 7. 10.]]


In [19]:
x = tf.constant([[0],[10],[20],[30]])
y = tf.constant([0,1,2])

print((x+y).numpy())

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [20]:
x = tf.constant([[0],[10],[20],[30]])
y = tf.constant([0,1,2])

print((x+y).numpy())

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [21]:
import numpy as np
print(np.arange(3))
print(np.ones((3,3)))
print()

x = tf.constant(np.arange(3))
y = tf.constant([5], dtype=tf.int64)
print(x)
print(y)
print(x+y)

[0 1 2]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

tf.Tensor([0 1 2], shape=(3,), dtype=int64)
tf.Tensor([5], shape=(1,), dtype=int64)
tf.Tensor([5 6 7], shape=(3,), dtype=int64)


In [23]:
x = tf.constant(np.arange(3))
y = tf.constant([5], dtype=tf.int64)
print((x+y).numpy())


x = tf.constant(np.ones((3,3)))
y = tf.constant(np.arange(3), dtype=tf.double)
print((x+y).numpy())

x = tf.constant(np.arange(3).reshape(3,1))
y = tf.constant(np.arange(3))
print((x+y).numpy())

[5 6 7]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [24]:
a =2
b = 3
c = tf.add(a,b)
print(c.numpy())

5


In [25]:
tf.pow(5,6)

<tf.Tensor: shape=(), dtype=int32, numpy=15625>

In [26]:
a = tf. constant(2.)
b = tf. constant(3.)
c = tf. constant(5.)

mean = tf.reduce_mean([a,b,c])
sum = tf.reduce_sum([a,b,c])

print("mean = ", mean.numpy())
print("sum = ", sum.numpy())

mean =  3.3333333
sum =  10.0


In [27]:
print(a)

print(a.numpy())
print(b)
print(b.numpy())
print(a*b)

tf.Tensor(2.0, shape=(), dtype=float32)
2.0
tf.Tensor(3.0, shape=(), dtype=float32)
3.0
tf.Tensor(6.0, shape=(), dtype=float32)


In [28]:
import numpy as np

c = np.multiply(a,b)
print(c)

6.0


In [29]:
my_image = tf.zeros([2,5,5,3])
my_image.shape

TensorShape([2, 5, 5, 3])

In [30]:
tf.rank(my_image)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [31]:
rank_three_tensor = tf.ones([3,4,5])
rank_three_tensor.shape

TensorShape([3, 4, 5])

In [32]:
rank_three_tensor.numpy()

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float32)

In [33]:
matrix = tf.reshape(rank_three_tensor, [6,10])
matrix

<tf.Tensor: shape=(6, 10), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [35]:
matrixB = tf.reshape(matrix, [3, -1])

In [36]:
matrixAlt = tf.reshape(matrixB, [4,3,-1])
matrixAlt

<tf.Tensor: shape=(4, 3, 5), dtype=float32, numpy=
array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float32)>

In [37]:
yet_another = tf.reshape(matrixAlt, [13,2,-1])

InvalidArgumentError: ignored

In [38]:
float_tensor = tf.cast(tf.constant([1,2,3]),dtype=tf.float32)
float_tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [39]:
float_tensor.dtype

tf.float32

In [40]:
v = tf.Variable(0.0)
v

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.0>

In [41]:
w = v + 10
w

<tf.Tensor: shape=(), dtype=float32, numpy=10.0>

In [42]:
w.numpy()

10.0

In [43]:
v = tf.Variable(2.0)
v.assign_add(5)
v

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=7.0>

In [44]:
v.read_value()

<tf.Tensor: shape=(), dtype=float32, numpy=7.0>